// Database Types - Generated from Supabase Schema

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          first_name: string;
          last_name: string;
          phone: string | null;
          role: 'CEO' | 'SUPER_ADMIN' | 'ADMIN' | 'CONTRACTOR';
          is_active: boolean;
          is_email_verified: boolean;
          must_reset_password: boolean;
          last_login_at: string | null;
          mfa_enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          first_name: string;
          last_name: string;
          phone?: string | null;
          role?: 'CEO' | 'SUPER_ADMIN' | 'ADMIN' | 'CONTRACTOR';
          is_active?: boolean;
          is_email_verified?: boolean;
          must_reset_password?: boolean;
          last_login_at?: string | null;
          mfa_enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          first_name?: string;
          last_name?: string;
          phone?: string | null;
          role?: 'CEO' | 'SUPER_ADMIN' | 'ADMIN' | 'CONTRACTOR';
          is_active?: boolean;
          is_email_verified?: boolean;
          must_reset_password?: boolean;
          last_login_at?: string | null;
          mfa_enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      contractors: {
        Row: {
          id: string;
          profile_id: string;
          business_name: string;
          business_type: string | null;
          tax_id: string | null;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          state: string | null;
          zip_code: string | null;
          business_phone: string | null;
          business_email: string | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          onboarding_status: string;
          onboarding_completed_at: string | null;
          approved_by: string | null;
          approved_at: string | null;
          is_eligible_for_assignment: boolean;
          eligibility_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          business_name: string;
          business_type?: string | null;
          tax_id?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          business_phone?: string | null;
          business_email?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          onboarding_status?: string;
          onboarding_completed_at?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          is_eligible_for_assignment?: boolean;
          eligibility_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          business_name?: string;
          business_type?: string | null;
          tax_id?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          business_phone?: string | null;
          business_email?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          onboarding_status?: string;
          onboarding_completed_at?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          is_eligible_for_assignment?: boolean;
          eligibility_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      storm_events: {
        Row: {
          id: string;
          event_code: string;
          name: string;
          utility_client: string;
          status: string;
          region: string | null;
          contract_reference: string | null;
          start_date: string | null;
          end_date: string | null;
          notes: string | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          event_code: string;
          name: string;
          utility_client: string;
          status?: string;
          region?: string | null;
          contract_reference?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          notes?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          event_code?: string;
          name?: string;
          utility_client?: string;
          status?: string;
          region?: string | null;
          contract_reference?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          notes?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      tickets: {
        Row: {
          id: string;
          storm_event_id: string | null;
          ticket_number: string;
          status: string;
          priority: string;
          address: string;
          latitude: number | null;
          longitude: number | null;
          geofence_radius_meters: number;
          assigned_to: string | null;
          assigned_by: string | null;
          assigned_at: string | null;
          created_at: string;
          scheduled_date: string | null;
          due_date: string | null;
          utility_client: string;
          work_description: string | null;
          created_by: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          storm_event_id?: string | null;
          ticket_number: string;
          status?: string;
          priority?: string;
          address: string;
          latitude?: number | null;
          longitude?: number | null;
          geofence_radius_meters?: number;
          assigned_to?: string | null;
          assigned_by?: string | null;
          assigned_at?: string | null;
          created_at?: string;
          scheduled_date?: string | null;
          due_date?: string | null;
          utility_client: string;
          work_description?: string | null;
          created_by: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          storm_event_id?: string | null;
          ticket_number?: string;
          status?: string;
          priority?: string;
          address?: string;
          latitude?: number | null;
          longitude?: number | null;
          geofence_radius_meters?: number;
          assigned_to?: string | null;
          assigned_by?: string | null;
          assigned_at?: string | null;
          created_at?: string;
          scheduled_date?: string | null;
          due_date?: string | null;
          utility_client?: string;
          work_description?: string | null;
          created_by?: string;
          updated_at?: string;
        };
      };
      time_entries: {
        Row: {
          id: string;
          contractor_id: string;
          ticket_id: string | null;
          clock_in_at: string;
          clock_in_latitude: number | null;
          clock_in_longitude: number | null;
          clock_out_at: string | null;
          clock_out_latitude: number | null;
          clock_out_longitude: number | null;
          work_type: string;
          work_type_rate: number;
          total_minutes: number | null;
          break_minutes: number;
          billable_minutes: number | null;
          billable_amount: number | null;
          status: string;
          reviewed_by: string | null;
          reviewed_at: string | null;
          rejection_reason: string | null;
          invoice_id: string | null;
          sync_status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          contractor_id: string;
          ticket_id?: string | null;
          clock_in_at: string;
          clock_in_latitude?: number | null;
          clock_in_longitude?: number | null;
          clock_out_at?: string | null;
          clock_out_latitude?: number | null;
          clock_out_longitude?: number | null;
          work_type: string;
          work_type_rate: number;
          total_minutes?: number | null;
          break_minutes?: number;
          billable_minutes?: number | null;
          billable_amount?: number | null;
          status?: string;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          rejection_reason?: string | null;
          invoice_id?: string | null;
          sync_status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          contractor_id?: string;
          ticket_id?: string | null;
          clock_in_at?: string;
          clock_in_latitude?: number | null;
          clock_in_longitude?: number | null;
          clock_out_at?: string | null;
          clock_out_latitude?: number | null;
          clock_out_longitude?: number | null;
          work_type?: string;
          work_type_rate?: number;
          total_minutes?: number | null;
          break_minutes?: number;
          billable_minutes?: number | null;
          billable_amount?: number | null;
          status?: string;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          rejection_reason?: string | null;
          invoice_id?: string | null;
          sync_status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}
