'use client';
import {useCallback,useEffect,useState} from 'react';
import {Users,ArrowRight} from 'lucide-react';
import {toast} from 'sonner';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {useAuth} from '@/components/providers/AuthProvider';
import {ticketAssessmentWorkflow,type DispatchOptions} from '@/lib/services/ticketAssessmentWorkflow';
import type {Ticket} from '@/types';
const selectClass='min-h-11 w-full rounded-lg border bg-background px-3 text-sm';
export function TicketDispatch({ticket,onChanged}:{ticket:Ticket;onChanged:()=>void}){
  const {profile,can}=useAuth();const [options,setOptions]=useState<DispatchOptions|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const [lead,setLead]=useState('');const [crew,setCrew]=useState('');const [driver,setDriver]=useState('');const [assessor,setAssessor]=useState('');const [name,setName]=useState('');const [creating,setCreating]=useState(false);
  const chief=profile?.role==='CEO'||profile?.role==='SUPER_ADMIN';const editable=can('admin.tickets.edit')&&['DRAFT','ASSIGNED','NEEDS_REWORK'].includes(ticket.status);
  const load=useCallback(async()=>{try{setOptions(await ticketAssessmentWorkflow.options(ticket.id));setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to load dispatch.');}},[ticket.id]);
  useEffect(()=>{void Promise.resolve().then(load);},[load,ticket.team_lead_id,ticket.crew_id]);
  const run=async(fn:()=>Promise<unknown>,message:string)=>{setBusy(true);try{await fn();toast.success(message);await load();onChanged();}catch(e){setError(e instanceof Error?e.message:'Dispatch failed.');}finally{setBusy(false);}};
  const assignedCrew=options?.crews.find(c=>c.id===ticket.crew_id);const team=options?.teamLeads.find(l=>l.id===ticket.team_lead_id);
  return <section id="dispatch" className="cc-work-panel scroll-mt-24 p-5"><div className="flex items-center gap-2"><Users className="size-5 text-grid-blue"/><h2 className="font-heading text-xl font-semibold text-grid-navy">Team & crew</h2></div><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-xs text-muted-foreground">Team lead</dt><dd className="mt-1 font-semibold">{team?.name||(ticket.team_lead_id?'Assigned team lead':'Awaiting team lead')}</dd></div><div><dt className="text-xs text-muted-foreground">Crew</dt><dd className="mt-1 font-semibold">{assignedCrew?.name||(ticket.crew_id?'Assigned crew':'Awaiting crew')}</dd></div>{assignedCrew&&<><div><dt className="text-xs text-muted-foreground">Driver</dt><dd>{assignedCrew.driverName}</dd></div><div><dt className="text-xs text-muted-foreground">Damage assessor</dt><dd>{assignedCrew.assessorName}</dd></div></>}</dl>
    {editable&&options&&<fieldset disabled={busy} className="mt-5 space-y-4 border-t pt-4">
      {chief&&<div className="space-y-2"><Label htmlFor="dispatch-lead">Pass to team lead</Label><select id="dispatch-lead" className={selectClass} value={lead} onChange={e=>setLead(e.target.value)}><option value="">Select a team lead</option>{options.teamLeads.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select>{!options.teamLeads.length&&<p className="text-xs text-muted-foreground">No active Admin team lead accounts yet. A storm manager must provision a staff account with the Team lead (Admin) role before dispatch.</p>}<Button className="w-full" disabled={!lead||busy} onClick={()=>void run(()=>ticketAssessmentWorkflow.assignLead(ticket.id,lead),'Ticket passed to team lead')}>Assign team lead<ArrowRight/></Button></div>}
      {ticket.team_lead_id&&<><div className="space-y-2"><Label htmlFor="dispatch-crew">Assign a crew</Label><select id="dispatch-crew" className={selectClass} value={crew} onChange={e=>setCrew(e.target.value)}><option value="">Select a driver / assessor crew</option>{options.crews.filter(c=>c.teamLeadId===ticket.team_lead_id).map(c=><option key={c.id} value={c.id}>{c.name} · {c.driverName} / {c.assessorName}</option>)}</select><Button className="w-full" disabled={!crew||busy} onClick={()=>void run(()=>ticketAssessmentWorkflow.assignCrew(ticket.id,crew),'Ticket assigned to crew')}>Assign crew<ArrowRight/></Button></div><Button variant="outline" className="w-full" onClick={()=>setCreating(v=>!v)}>{creating?'Cancel crew setup':'Create a crew'}</Button></>}
      {creating&&ticket.team_lead_id&&<div className="space-y-3 rounded-xl bg-grid-shell p-3"><Label htmlFor="crew-name">Crew name</Label><Input id="crew-name" value={name} onChange={e=>setName(e.target.value)} maxLength={100} placeholder="Crew 01"/><Label htmlFor="crew-driver">Driver</Label><select id="crew-driver" className={selectClass} value={driver} onChange={e=>setDriver(e.target.value)}><option value="">Choose driver</option>{options.workers.filter(w=>w.role==='DRIVER'&&!options.crews.some(c=>c.driverId===w.id)).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><Label htmlFor="crew-assessor">Damage assessor</Label><select id="crew-assessor" className={selectClass} value={assessor} onChange={e=>setAssessor(e.target.value)}><option value="">Choose assessor</option>{options.workers.filter(w=>['DAMAGE_ASSESSER','SR_DAMAGE_ASSESSER'].includes(w.role)&&!options.crews.some(c=>c.assessorId===w.id)).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><p className="text-xs text-muted-foreground">Both contractors must be active, onboarded, and eligible. Each belongs to one active crew for this storm.</p><Button disabled={!name.trim()||!driver||!assessor||busy} className="w-full" onClick={()=>void run(async()=>{await ticketAssessmentWorkflow.createCrew(ticket.id,ticket.team_lead_id!,driver,assessor,name);setCreating(false);setDriver('');setAssessor('');setName('');},'Crew created. Select it to assign the ticket.')}><Users/>Save crew</Button></div>}
    </fieldset>}{error&&<p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}
  </section>;
}
