import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { CapturedAssessmentPhoto } from '@/types';
import type { LocalEntergyRecord } from './entergyFormService';
import { emptyEntergyPayload } from '@/lib/schemas/entergyForms';
const mocks=vi.hoisted(()=>({rows:new Map<string,LocalEntergyRecord>(),actor:'actor',remote:[] as LocalEntergyRecord['record'][],rpc:vi.fn(),upload:vi.fn(),addPhoto:vi.fn(),deleteEditing:vi.fn()}));
vi.mock('@/lib/db/dexie',()=>({db:{
  entergyForms:{get:async(id:string)=>mocks.rows.get(id),put:async(row:LocalEntergyRecord)=>mocks.rows.set(row.id,row),bulkPut:async(rows:LocalEntergyRecord[])=>rows.forEach(r=>mocks.rows.set(r.id,r)),delete:async(id:string)=>mocks.rows.delete(id),update:async(id:string,patch:Partial<LocalEntergyRecord>)=>{const r=mocks.rows.get(id);if(r)mocks.rows.set(id,{...r,...patch});},where:()=>({equals:(actor:string)=>({toArray:async()=>Array.from(mocks.rows.values()).filter(r=>r.actor_profile_id===actor)})})},
  entergyEditing:{delete:mocks.deleteEditing},photos:{get:async()=>undefined},
}}));
vi.mock('@/lib/supabase/client',()=>({supabase:{auth:{getUser:async()=>({data:{user:{id:mocks.actor}},error:null})},from:()=>{const query={select:()=>query,eq:()=>query,order:async()=>({data:mocks.remote,error:null})};return query;}}}));
vi.mock('@/lib/services/ticketAssessmentWorkflow',()=>({ticketWorkflowRpc:mocks.rpc,ticketAssessmentWorkflow:{restorePhotos:vi.fn()}}));
vi.mock('@/lib/sync/photoUploadQueue',()=>({photoUploadQueue:{add:mocks.addPhoto,process:mocks.upload}}));
import { entergyFormService } from './entergyFormService';
const clean=()=>{const p=emptyEntergyPayload('cleanup');Object.assign(p.answers,{environmentalCleanup:'None',trashCleanup:'Wood: 2',address:'100 Utility Lane',cityTown:'Shreveport',dloc:'00001234',truckAccess:false,notes:'None'});return p;};
const input=()=>({id:'form',ticketId:'ticket',actor:'actor',kind:'cleanup' as const,payload:clean(),photos:[] as CapturedAssessmentPhoto[],version:null});
const photos=()=>['OVERVIEW','EQUIPMENT','DAMAGE','SAFETY'].map((type,i)=>({id:`photo-${i}`,type,ticketId:'ticket',file:new File(['data'],'evidence.jpg',{type:'image/jpeg'}),previewUrl:'blob:preview',capturedAt:'2026-10-06',checksumSha256:'checksum',metadata:{gpsLatitude:32.4,gpsLongitude:-93.7,capturedAt:'2026-10-06',deviceMake:null,deviceModel:null},originalSizeBytes:4,sizeBytes:4,compressed:false,isDuplicate:false}) as CapturedAssessmentPhoto);
beforeEach(()=>{mocks.rows.clear();mocks.remote=[];mocks.actor='actor';vi.clearAllMocks();Object.defineProperty(navigator,'onLine',{value:true,configurable:true});mocks.rpc.mockImplementation(async(_name,args)=>({id:args.p_id,ticket_id:args.p_ticket_id,form_kind:args.p_kind,payload:args.p_payload,photo_evidence:args.p_photos,status:args.p_submit?'SUBMITTED':'DRAFT',version:(args.p_expected_version??0)+1,saved_at:'2026-10-06T12:00:00Z',created_at:'2026-10-06T12:00:00Z',created_by:'actor',saved_by:'actor',submitted_at:args.p_submit?'2026-10-06T12:00:00Z':null}));});
describe('Entergy saved records and reconnect',()=>{
  it('saves each form kind independently against the same ticket',async()=>{await entergyFormService.save(input());await entergyFormService.save({...input(),id:'damage',kind:'damage',payload:emptyEntergyPayload('damage')});expect(mocks.rows.size).toBe(2);expect(mocks.rpc.mock.calls.map(c=>c[1].p_kind)).toEqual(['cleanup','damage']);});
  it('keeps incomplete offline drafts and explicit submit intent separate',async()=>{Object.defineProperty(navigator,'onLine',{value:false});const draft=await entergyFormService.save({...input(),payload:emptyEntergyPayload('cleanup')});expect(draft.dirty).toBe(true);expect(draft.submit_requested).toBe(false);expect(mocks.rpc).not.toHaveBeenCalled();});
  it('uploads queued evidence before submitting and preserves stable IDs and ticket linkage',async()=>{const p=photos();const saved=await entergyFormService.save({...input(),photos:p,submit:true});expect(saved.record.status).toBe('SUBMITTED');expect(mocks.addPhoto).toHaveBeenCalledTimes(4);expect(mocks.upload).toHaveBeenCalledTimes(1);expect(mocks.rpc.mock.calls[0][1].p_photos.map((e:{id:string})=>e.id)).toEqual(p.map(x=>x.id));expect(mocks.deleteEditing).toHaveBeenCalledWith('actor:ticket:cleanup');});
  it('reconnects only records belonging to the verified actor',async()=>{Object.defineProperty(navigator,'onLine',{value:false});await entergyFormService.save(input());await entergyFormService.save({...input(),id:'other',actor:'other'});Object.defineProperty(navigator,'onLine',{value:true});const result=await entergyFormService.process('actor');expect(result.pending).toBe(0);expect(mocks.rpc).toHaveBeenCalledTimes(1);expect(mocks.rows.get('other:other')?.dirty).toBe(true);});
  it('fails a changed login without sending saved data as the other user',async()=>{Object.defineProperty(navigator,'onLine',{value:false});await entergyFormService.save(input());Object.defineProperty(navigator,'onLine',{value:true});mocks.actor='other';await expect(entergyFormService.process('actor')).rejects.toThrow('account mismatch');expect(mocks.rpc).not.toHaveBeenCalled();});
  it('keeps conflicting edits durable and does not retry with a newer version silently',async()=>{mocks.rpc.mockRejectedValue(new Error('This form changed on another device'));await expect(entergyFormService.save({...input(),version:3})).rejects.toThrow('Saved on this device');const local=mocks.rows.get('actor:form');expect(local?.dirty).toBe(true);expect(local?.expected_version).toBe(3);expect(local?.last_error).toContain('another device');});
  it('preserves offline submissions through retry and prevents editing queued records',async()=>{Object.defineProperty(navigator,'onLine',{value:false});const saved=await entergyFormService.save({...input(),photos:photos(),submit:true});expect(saved.submit_requested).toBe(true);await expect(entergyFormService.save(input())).rejects.toThrow('submitted or queued');Object.defineProperty(navigator,'onLine',{value:true});await entergyFormService.process('actor');expect(mocks.rows.get('actor:form')?.record.status).toBe('SUBMITTED');});
  it('reads the actor-scoped cache offline and preserves unsynced records during online list refresh',async()=>{Object.defineProperty(navigator,'onLine',{value:false});await entergyFormService.save(input());expect(await entergyFormService.list('ticket','other')).toEqual([]);Object.defineProperty(navigator,'onLine',{value:true});expect((await entergyFormService.list('ticket','actor'))[0].dirty).toBe(true);});
});
