import { supabase } from '@/lib/supabase/client';
import { db, type TicketDraftSnapshot } from '@/lib/db/dexie';
import { photoUploadQueue } from '@/lib/sync/photoUploadQueue';
import { normalizeFieldAnswers, type AssessmentPhotoEvidence, type FieldAssessment } from '@/lib/schemas/fieldAssessment';
import { notifyTicketsChanged } from '@/lib/tickets/events';
import type { CapturedAssessmentPhoto, Ticket } from '@/types';

export interface SubmittedTicketAssessment {
  id: string; ticket_id: string; contractor_id: string; field_assessment: FieldAssessment;
  photo_evidence: AssessmentPhotoEvidence[]; created_at: string;
  review_stage: 'TEAM_LEAD_REVIEW' | 'FINAL_REVIEW' | 'APPROVED' | 'NEEDS_REWORK';
  team_review_notes?: string; review_notes?: string;
}
export interface RemoteTicketDraft {
  ticket_id: string; assessment_id: string; contractor_id: string; field_assessment: FieldAssessment;
  photo_evidence: AssessmentPhotoEvidence[]; version: number; saved_at: string;
}
export interface DispatchOptions {
  teamLeads: { id: string; name: string }[];
  crews: { id: string; name: string; teamLeadId: string; driverId: string; assessorId: string; driverName: string; assessorName: string }[];
  workers: { id: string; name: string; role: string }[];
}
export async function ticketWorkflowRpc<T>(name: string, args: Record<string, unknown>): Promise<T> {
  // RPCs are generated by the workflow migration; authorization and identity binding happen in Postgres.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (supabase as any).rpc(name, args);
  if (error) throw new Error(error.message);
  if(!['ticket_dispatch_options','mark_ticket_notification_read'].includes(name))notifyTicketsChanged();
  return (Array.isArray(data) ? data[0] : data) as T;
}
const online = () => typeof navigator === 'undefined' || navigator.onLine;
const key = (actor: string, ticket: string) => `${actor}:${ticket}`;
let lock = Promise.resolve();
function exclusive<T>(operation: () => Promise<T>): Promise<T> {
  const result = lock.then(operation); lock = result.then(() => undefined, () => undefined); return result;
}
async function signedInActor(): Promise<string> {
  const {data, error} = await supabase.auth.getUser();
  if (error || !data.user) throw new Error('Sign in to sync your ticket assessment.');
  return data.user.id;
}
function fromRemote(d: RemoteTicketDraft, actor: string): TicketDraftSnapshot {
  return { ...d, id: key(actor,d.ticket_id), actor_profile_id: actor, dirty: false, submit_requested: false };
}
async function persistRemote(d: TicketDraftSnapshot): Promise<TicketDraftSnapshot> {
  const row = await ticketWorkflowRpc<RemoteTicketDraft>('save_ticket_assessment_draft', {
    p_ticket_id:d.ticket_id,p_assessment_id:d.assessment_id,p_payload:d.field_assessment,p_photos:d.photo_evidence,p_expected_version:d.version,
  });
  const saved = {...d,version:row.version,saved_at:row.saved_at,dirty:false,last_error:undefined};
  await db.ticketDraftQueue.put(saved); return saved;
}
async function finishSubmission(d: TicketDraftSnapshot): Promise<void> {
  await ticketWorkflowRpc<SubmittedTicketAssessment>('submit_ticket_assessment',{p_ticket_id:d.ticket_id,p_assessment_id:d.assessment_id,p_expected_version:d.version});
  await db.ticketDraftQueue.delete(d.id);
  await db.assessmentDrafts.delete(`${d.actor_profile_id}:${d.contractor_id}:${d.ticket_id}`);
  await db.assessmentDrafts.delete(`${d.contractor_id}:${d.ticket_id}`);
}
export const ticketAssessmentWorkflow = {
  async loadDraft(ticketId: string, actor: string, preferServer=false): Promise<TicketDraftSnapshot | null> {
    const local = await db.ticketDraftQueue.get(key(actor,ticketId));
    if (!online()) return local ?? null;
    // A dirty saved snapshot belongs to this actor and stays available for conflict recovery.
    if (!preferServer && (local?.dirty || local?.submit_requested)) return local;
    const {data,error} = await supabase.from('ticket_assessment_drafts').select('*').eq('ticket_id',ticketId).maybeSingle();
    if (error) throw new Error(error.message);
    if (!data) { if(local) await db.ticketDraftQueue.delete(local.id); return null; }
    const remote = fromRemote(data as unknown as RemoteTicketDraft,actor);
    if (local?.assessment_id===remote.assessment_id && local.version===remote.version && JSON.stringify(local.photo_evidence)===JSON.stringify(remote.photo_evidence)) remote.photos=local.photos;
    await db.ticketDraftQueue.put(remote); return remote;
  },
  async restorePhotos(d: {ticket_id:string;photo_evidence:AssessmentPhotoEvidence[];photos?:CapturedAssessmentPhoto[]}): Promise<CapturedAssessmentPhoto[]> {
    if (d.photos?.length===d.photo_evidence.length && d.photo_evidence.every(e=>d.photos!.some(p=>p.id===e.id))) return d.photos.map(p=>({...p,previewUrl:URL.createObjectURL(p.file)}));
    if(!online()) throw new Error('These photos are not stored on this device. Reconnect to open this assessment.');
    const {data,error}=await supabase.from('media_assets').select('id,storage_path,checksum_sha256,captured_at').eq('entity_type','ticket').eq('entity_id',d.ticket_id).in('id',d.photo_evidence.map(p=>p.id));
    if(error) throw new Error(error.message);
    const restored: CapturedAssessmentPhoto[]=[];
    try { for(const evidence of d.photo_evidence) {
      const m=data?.find(m=>m.id===evidence.id); if(!m) throw new Error('Linked photo metadata is unavailable. Sync or reload the ticket.');
      const {data:blob,error:downloadError}=await supabase.storage.from('assessment-photos').download(m.storage_path);
      if(downloadError||!blob) throw new Error('Unable to restore private ticket evidence. Reconnect and retry.');
      const file=new File([blob],m.storage_path.split('/').pop()||'photo.jpg',{type:blob.type});
      restored.push({id:evidence.id,ticketId:d.ticket_id,type:evidence.type as CapturedAssessmentPhoto['type'],sectionKey:evidence.sectionKey,file,previewUrl:URL.createObjectURL(file),remotePersisted:true,capturedAt:m.captured_at??'',metadata:{gpsLatitude:evidence.gpsLatitude??null,gpsLongitude:evidence.gpsLongitude??null,capturedAt:m.captured_at,deviceMake:null,deviceModel:null},checksumSha256:m.checksum_sha256??'',originalSizeBytes:file.size,sizeBytes:file.size,compressed:false,isDuplicate:false});
    } return restored; } catch(error) { restored.forEach(p=>URL.revokeObjectURL(p.previewUrl));throw error; }
  },
  save(input: {ticketId:string;contractorId:string;actor:string;assessmentId:string;version:number|null;fieldAssessment:FieldAssessment;photos:CapturedAssessmentPhoto[]}): Promise<TicketDraftSnapshot> {
    return exclusive(async()=>{
      const old=await db.ticketDraftQueue.get(key(input.actor,input.ticketId));
      if(old?.submit_requested) throw new Error('Submission is queued. Sync the ticket before editing again.');
      const photos=input.photos.map(p=>({...p,actorProfileId:input.actor}));
      for(const photo of photos) if(!photo.remotePersisted) await photoUploadQueue.add(photo);
      const d:TicketDraftSnapshot={id:key(input.actor,input.ticketId),actor_profile_id:input.actor,ticket_id:input.ticketId,contractor_id:input.contractorId,assessment_id:input.assessmentId,field_assessment:{version:1,answers:normalizeFieldAnswers(input.fieldAssessment.answers)},photo_evidence:photos.map(p=>({id:p.id,type:p.type,sectionKey:p.sectionKey,checksumSha256:p.checksumSha256,gpsLatitude:p.metadata.gpsLatitude??undefined,gpsLongitude:p.metadata.gpsLongitude??undefined})),photos,version:input.version,dirty:true,submit_requested:false,saved_at:new Date().toISOString()};
      await db.ticketDraftQueue.put(d);
      if(online()) { try { if(await signedInActor()!==input.actor) throw new Error('Your signed-in account changed. Reload the ticket.');return await persistRemote(d); } catch(error) {const message=error instanceof Error?error.message:'Draft sync failed';await db.ticketDraftQueue.update(d.id,{last_error:message});throw new Error(`Saved on this device, but could not sync: ${message}`);} }
      return d;
    });
  },
  submit(ticketId:string,actor:string,assessmentId:string):Promise<'SUBMITTED'|'QUEUED'> {
    return exclusive(async()=>{
      let d=await db.ticketDraftQueue.get(key(actor,ticketId));
      if(!d||d.assessment_id!==assessmentId) throw new Error('Reload and review the saved draft before submitting.');
      if(!online()) {await db.ticketDraftQueue.update(d.id,{submit_requested:true,last_error:undefined});return 'QUEUED';}
      if(await signedInActor()!==actor) throw new Error('Your signed-in account changed. Reload the ticket.');
      if(d.dirty) d=await persistRemote(d);
      await photoUploadQueue.process();
      await finishSubmission(d);return 'SUBMITTED';
    });
  },
  process(actor:string): Promise<{failed:number;pending:number;errors:string[]}> {
    return exclusive(async()=>{
      const rows=await db.ticketDraftQueue.where('actor_profile_id').equals(actor).toArray();let failed=0;const errors:string[]=[];
      if(!online()) return {failed:0,pending:rows.filter(r=>r.dirty||r.submit_requested).length,errors};
      if(await signedInActor()!==actor) throw new Error('Assessment sync account mismatch.');
      for(let d of rows.filter(r=>r.dirty||r.submit_requested)) {try {if(d.dirty)d=await persistRemote(d);if(d.submit_requested)await finishSubmission(d);}catch(error){failed++;const message=error instanceof Error?error.message:'Ticket assessment sync failed';errors.push(message);await db.ticketDraftQueue.update(d.id,{last_error:message});}}
      const pending=(await db.ticketDraftQueue.where('actor_profile_id').equals(actor).toArray()).filter(r=>r.dirty||r.submit_requested).length;
      return {failed,pending,errors};
    });
  },
  async loadAssessments(ticketId:string):Promise<SubmittedTicketAssessment[]> {
    if(!online()) return db.ticketAssessmentHistory.where('ticket_id').equals(ticketId).reverse().sortBy('created_at');
    const {data,error}=await supabase.from('damage_assessments').select('*').eq('ticket_id',ticketId).order('created_at',{ascending:false});
    if(error)throw new Error(error.message);const rows=(data??[]) as unknown as SubmittedTicketAssessment[];await db.ticketAssessmentHistory.bulkPut(rows);return rows;
  },
  review(assessmentId:string,decision:'APPROVED'|'NEEDS_REWORK',notes:string) {return ticketWorkflowRpc<SubmittedTicketAssessment>('review_ticket_assessment',{p_assessment_id:assessmentId,p_decision:decision,p_notes:notes});},
  options(ticketId:string) {return ticketWorkflowRpc<DispatchOptions>('ticket_dispatch_options',{p_ticket_id:ticketId});},
  assignLead(ticketId:string,leadId:string) {return ticketWorkflowRpc<Ticket>('assign_ticket_team_lead',{p_ticket_id:ticketId,p_team_lead_id:leadId});},
  createCrew(ticketId:string,leadId:string,driverId:string,assessorId:string,name:string) {return ticketWorkflowRpc<DispatchOptions['crews'][number]>('create_field_crew',{p_ticket_id:ticketId,p_team_lead_id:leadId,p_driver_id:driverId,p_assessor_id:assessorId,p_name:name});},
  assignCrew(ticketId:string,crewId:string) {return ticketWorkflowRpc<Ticket>('assign_ticket_crew',{p_ticket_id:ticketId,p_crew_id:crewId});},
  handoff(ticketId:string,reference:string) {return ticketWorkflowRpc<Ticket>('record_ticket_utility_handoff',{p_ticket_id:ticketId,p_reference:reference});},
};
