// Central Command - Application Configuration

export const APP_CONFIG = {
  // Time tracking
  MAX_TIME_ENTRY_HOURS: 24,
  WARNING_TIME_ENTRY_HOURS: 8,
  AUTO_CLOCK_OUT_ENABLED: false,
  
  // GPS
  GEOFENCE_RADIUS_METERS: 500,
  MIN_GPS_ACCURACY_METERS: 100,
  MAX_GPS_ACCURACY_METERS: 500,
  GPS_UPDATE_INTERVAL_MS: 30000, // 30 seconds
  
  // Photos
  MAX_PHOTO_SIZE_MB: 10,
  MIN_PHOTOS_REQUIRED: 4,
  PHOTO_QUALITY: 0.85,
  MAX_PHOTO_WIDTH: 1920,
  MAX_PHOTO_HEIGHT: 1080,
  
  // Validation
  REQUIRE_PHOTO_GPS: true,
  REQUIRE_SERVER_TIMESTAMP: true,
  ENABLE_DUPLICATE_DETECTION: true,
  ENABLE_GPS_SPOOFING_DETECTION: true,
  
  // Expenses
  RECEIPT_REQUIRED_THRESHOLD: 25,
  AUTO_APPROVE_THRESHOLD: 75,
  MILEAGE_RATE: 0.655, // IRS rate
  
  
  // Pagination
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  
  // Offline
  MAX_SYNC_RETRY_ATTEMPTS: 5,
  SYNC_RETRY_DELAY_MS: 5000,

  // Payroll & utility billing
  VEHICLE_REIMBURSEMENT_HOURLY_RATE: 5,
  PAYROLL_PERIOD_DEFAULT_DAYS: 14,
} as const;

// Role definitions
export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  TEAM_LEAD: 'TEAM_LEAD',
  CONTRACTOR: 'CONTRACTOR',
  READ_ONLY: 'READ_ONLY',
} as const;

// Ticket statuses
export const TICKET_STATUSES = {
  DRAFT: 'DRAFT',
  ASSIGNED: 'ASSIGNED',
  IN_ROUTE: 'IN_ROUTE',
  ON_SITE: 'ON_SITE',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETE: 'COMPLETE',
  PENDING_REVIEW: 'PENDING_REVIEW',
  APPROVED: 'APPROVED',
  NEEDS_REWORK: 'NEEDS_REWORK',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED',
  EXPIRED: 'EXPIRED',
} as const;

// Work types
export const WORK_TYPES = {
  STANDARD_ASSESSMENT: 'STANDARD_ASSESSMENT',
  EMERGENCY_RESPONSE: 'EMERGENCY_RESPONSE',
  TRAVEL: 'TRAVEL',
  STANDBY: 'STANDBY',
} as const;

// Contractor payroll roles — one per contractor, separate from
// profiles.role (the CEO/SUPER_ADMIN/ADMIN/CONTRACTOR authorization enum).
export const CONTRACTOR_ROLES = {
  STORM_MANAGER: 'STORM_MANAGER',
  TEAM_LEAD: 'TEAM_LEAD',
  SR_DAMAGE_ASSESSER: 'SR_DAMAGE_ASSESSER',
  DAMAGE_ASSESSER: 'DAMAGE_ASSESSER',
  DRIVER: 'DRIVER',
} as const;

export const ROLE_LABELS: Record<keyof typeof CONTRACTOR_ROLES, string> = {
  STORM_MANAGER: 'Storm Manager',
  TEAM_LEAD: 'Team Lead',
  SR_DAMAGE_ASSESSER: 'Sr. Damage Assessor',
  DAMAGE_ASSESSER: 'Damage Assessor',
  DRIVER: 'Driver',
};

// Vehicle reimbursement claim types
export const VEHICLE_TYPES = {
  PERSONAL: 'PERSONAL',
  RENTAL: 'RENTAL',
} as const;

export const VEHICLE_TYPE_LABELS: Record<keyof typeof VEHICLE_TYPES, string> = {
  PERSONAL: 'Personal Vehicle',
  RENTAL: 'Rental Vehicle',
};

// Expense categories
export const EXPENSE_CATEGORIES = {
  MILEAGE: 'MILEAGE',
  FUEL: 'FUEL',
  LODGING: 'LODGING',
  MEALS: 'MEALS',
  TOLLS: 'TOLLS',
  PARKING: 'PARKING',
  MATERIALS: 'MATERIALS',
  EQUIPMENT_RENTAL: 'EQUIPMENT_RENTAL',
  OTHER: 'OTHER',
} as const;

// Expense status
export const EXPENSE_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PAID: 'PAID',
} as const;

// Invoice status
export const INVOICE_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  PAID: 'PAID',
  VOID: 'VOID',
} as const;

// Equipment conditions
export const EQUIPMENT_CONDITIONS = {
  GOOD: 'GOOD',
  FAIR: 'FAIR',
  DAMAGED: 'DAMAGED',
  DESTROYED: 'DESTROYED',
} as const;

// Sync status
export const SYNC_STATUS = {
  SYNCED: 'SYNCED',
  PENDING: 'PENDING',
  FAILED: 'FAILED',
  CONFLICT: 'CONFLICT',
} as const;

// Notification types
export const NOTIFICATION_TYPES = {
  TICKET_ASSIGNED: 'TICKET_ASSIGNED',
  TICKET_UPDATED: 'TICKET_UPDATED',
  TIME_APPROVED: 'TIME_APPROVED',
  EXPENSE_APPROVED: 'EXPENSE_APPROVED',
  INVOICE_GENERATED: 'INVOICE_GENERATED',
  PAYMENT_PROCESSED: 'PAYMENT_PROCESSED',
  DOCUMENT_EXPIRING: 'DOCUMENT_EXPIRING',
  SAFETY_ALERT: 'SAFETY_ALERT',
} as const;
