import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { randomUUID } from 'node:crypto';
const runtime = process.env.CC_PGLITE_PATH || '/Users/davidmccarty/.codex/.chatgpt-projects/g-p-698e4e3dea2c819193d268ef77b9572e/workspace/e2e-20261001/policy-runtime/node_modules/@electric-sql/pglite/dist/index.js';
const { PGlite } = await import(pathToFileURL(runtime).href);
const db = new PGlite();
const legacyId = randomUUID();
const sa = randomUUID(), admin = randomUUID(), ceo = randomUUID();
let storm = randomUUID();
await db.exec(`CREATE SCHEMA private; CREATE SCHEMA auth; CREATE SCHEMA storage;
CREATE ROLE authenticated; CREATE ROLE anon; CREATE ROLE service_role BYPASSRLS;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('test.actor_id',true),'')::uuid $$;
CREATE TYPE contractor_role AS ENUM('STORM_MANAGER','TEAM_LEAD','SR_DAMAGE_ASSESSER','DAMAGE_ASSESSER','DRIVER');
CREATE TYPE user_role AS ENUM('CEO','SUPER_ADMIN','ADMIN','CONTRACTOR');
CREATE TABLE profiles(id uuid PRIMARY KEY,role user_role,is_active boolean DEFAULT true,must_reset_password boolean DEFAULT false);
CREATE FUNCTION private.active_profile_role() RETURNS text LANGUAGE sql SECURITY DEFINER AS $$ SELECT role::text FROM public.profiles WHERE id=auth.uid() AND is_active AND NOT must_reset_password $$;
CREATE TABLE private.permission_catalog(permission_key text PRIMARY KEY,admin_default boolean,privileged boolean);
CREATE TABLE user_permissions(profile_id uuid,permission_key text,effect text);
CREATE TABLE user_permission_versions(profile_id uuid);
INSERT INTO private.permission_catalog VALUES('admin.contractors.view',true,false),('admin.payroll.view',true,false),('admin.payroll.edit',false,false),('admin.time.view',true,false),('admin.time.edit',true,false),('admin.users.edit',false,true);
CREATE FUNCTION private.has_permission(uuid,text) RETURNS boolean LANGUAGE sql AS $$ SELECT private.active_profile_role() IN ('CEO','SUPER_ADMIN') $$;
CREATE TABLE contractors(id uuid PRIMARY KEY,profile_id uuid REFERENCES profiles(id),role contractor_role,is_deleted boolean DEFAULT false,is_eligible_for_assignment boolean DEFAULT true,onboarding_status text DEFAULT 'APPROVED');
CREATE TABLE contractor_rates(contractor_id uuid,work_type text,hourly_rate numeric,effective_from date,effective_to date);
CREATE TABLE role_rate_defaults(role contractor_role,work_type text,hourly_rate numeric);
CREATE TABLE utility_billing_rates(id uuid DEFAULT gen_random_uuid(),storm_event_id uuid,work_type text,hourly_rate numeric);
CREATE TABLE tickets(id uuid PRIMARY KEY,assigned_to uuid,storm_event_id uuid,is_deleted boolean DEFAULT false,status text DEFAULT 'ASSIGNED',updated_at timestamptz,updated_by uuid,address text);
CREATE TABLE ticket_status_history(ticket_id uuid,changed_by uuid);
CREATE TABLE audit_logs(action text,entity_type text,entity_id uuid,user_id uuid,user_role user_role,old_values jsonb,new_values jsonb,change_summary text);
CREATE TABLE storage.objects(id uuid DEFAULT gen_random_uuid(),bucket_id text,name text);
CREATE TABLE time_entries(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),contractor_id uuid,ticket_id uuid,storm_event_id uuid,
clock_in_at timestamptz,clock_out_at timestamptz,clock_in_latitude numeric,clock_in_longitude numeric,clock_in_accuracy numeric,clock_in_photo_url text,clock_in_ip inet,clock_in_user_agent text,
clock_out_latitude numeric,clock_out_longitude numeric,clock_out_accuracy numeric,clock_out_photo_url text,clock_out_ip inet,
work_type text,break_minutes integer DEFAULT 0,contractor_role contractor_role,work_type_rate numeric,pay_rate_applied numeric,payroll_amount numeric,utility_bill_rate_applied numeric,utility_bill_amount numeric,
status text DEFAULT 'PENDING',reviewed_by uuid,reviewed_at timestamptz,rejection_reason text,is_deleted boolean DEFAULT false,sync_status text DEFAULT 'SYNCED',created_at timestamptz DEFAULT now(),created_by uuid,updated_at timestamptz DEFAULT now(),
total_minutes integer GENERATED ALWAYS AS(extract(epoch FROM coalesce(clock_out_at,clock_in_at)-clock_in_at)/60) STORED,
billable_minutes integer GENERATED ALWAYS AS(extract(epoch FROM coalesce(clock_out_at,clock_in_at)-clock_in_at)/60-break_minutes) STORED);
CREATE TABLE time_entry_vehicle_claims(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),time_entry_id uuid UNIQUE,contractor_id uuid,vehicle_type text DEFAULT 'PERSONAL',declared_hours numeric,notes text,vehicle_photo_url text,license_plate_photo_url text,amount numeric DEFAULT 0,capped boolean DEFAULT false,status text DEFAULT 'PENDING',reviewed_by uuid,reviewed_at timestamptz,rejection_reason text);
CREATE FUNCTION private.apply_time_entry_costing() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RETURN NEW; END$$;
CREATE TRIGGER tr_apply_time_entry_costing BEFORE INSERT OR UPDATE ON time_entries FOR EACH ROW EXECUTE FUNCTION private.apply_time_entry_costing();
CREATE FUNCTION private.compute_vehicle_claim_amount() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RETURN NEW; END$$;
CREATE TRIGGER tr_compute_vehicle_claim_amount BEFORE INSERT OR UPDATE ON time_entry_vehicle_claims FOR EACH ROW EXECUTE FUNCTION private.compute_vehicle_claim_amount();
GRANT USAGE ON SCHEMA public,private,auth TO authenticated,service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
ALTER TABLE time_entries ENABLE ROW LEVEL SECURITY; ALTER TABLE contractors ENABLE ROW LEVEL SECURITY;
ALTER TABLE utility_billing_rates ENABLE ROW LEVEL SECURITY; ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY fixture_time ON time_entries FOR ALL TO authenticated USING(true) WITH CHECK(true);
CREATE POLICY fixture_contractors ON contractors FOR ALL TO authenticated USING(true) WITH CHECK(true);
CREATE POLICY fixture_profiles ON profiles FOR ALL TO authenticated USING(true) WITH CHECK(true);
CREATE POLICY fixture_billing ON utility_billing_rates FOR ALL TO authenticated USING(true) WITH CHECK(true);
GRANT SELECT ON contractors,profiles TO authenticated; GRANT UPDATE ON contractors TO authenticated;
`);
await db.query('INSERT INTO profiles(id,role) VALUES($1,\'SUPER_ADMIN\'),($2,\'ADMIN\'),($3,\'CEO\')',[sa,admin,ceo]);
await db.query("SELECT set_config('test.actor_id',$1,false)",[sa]);
await db.query("INSERT INTO profiles(id,role) VALUES($1,'CONTRACTOR')",[legacyId]);
await db.query("INSERT INTO contractors(id,profile_id,role) VALUES($1,$1,'DRIVER')",[legacyId]);
await db.query("INSERT INTO role_rate_defaults VALUES('DRIVER','STANDARD_ASSESSMENT',65),('DRIVER','TRAVEL',65)");
await db.query("INSERT INTO contractor_rates VALUES($1,'TRAVEL',75,current_date,NULL)",[legacyId]);
await db.query("INSERT INTO time_entries(contractor_id,clock_in_at,clock_out_at,work_type,work_type_rate,pay_rate_applied,payroll_amount,utility_bill_rate_applied,utility_bill_amount,contractor_role) VALUES($1,'2026-09-21T12:00Z','2026-09-21T13:00Z','TRAVEL',77,77,77,101,101,'DRIVER')",[legacyId]);
// Exact migration must compile against the fixture; the old proposal is not applied.
await db.exec(await readFile(new URL('../../supabase/migrations/20261004174918_configurable_contractor_time_payroll.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../../supabase/migrations/20261004185253_protect_closed_shift_evidence_and_agreement_boundaries.sql',import.meta.url),'utf8'));
await db.exec("GRANT EXECUTE ON FUNCTION private.has_permission(uuid,text) TO authenticated,service_role;");
let tests=[];
async function test(name,fn){await fn();tests.push(name);console.log(`PASS ${name}`);}
const initial='2027-01-04T06:00:00Z';
const terms=(policy={mode:'FLAT',multiplier:1},rate=65)=>({role:'DRIVER',base_hourly_rate:rate,work_type_rates:{},policy,driver_eligible:true,vehicle_allowance_enabled:true,vehicle_hourly_rate:5,week_start_day:1,timezone:'America/Chicago'});
async function agreement(id,at,value){return (await db.query('INSERT INTO contractor_pay_agreements(contractor_id,effective_from,terms) VALUES($1,$2,$3) RETURNING id',[id,at,value])).rows[0].id;}
async function worker(policy={mode:'FLAT',multiplier:1},role='DRIVER',rate=65){const id=randomUUID();await db.query("INSERT INTO profiles(id,role) VALUES($1,'CONTRACTOR')",[id]);await db.query("INSERT INTO contractors(id,profile_id,role) VALUES($1,$1,$2)",[id,role]);await db.query("INSERT INTO tickets(id,assigned_to,storm_event_id,address) VALUES($1,$1,$2,'QA')",[id,storm]);await agreement(id,initial,{...terms(policy,rate),role});return id;}
const interval=(kind,start,end)=>({id:randomUUID(),kind,start_at:start,end_at:end});
async function shift(worker,start,end,activities=[],type='TRAVEL'){
 const id=randomUUID(),inPhoto=`${worker}/time-entries/${id}/clock-in`,outPhoto=`${worker}/time-entries/${id}/clock-out`;
 await db.query("INSERT INTO storage.objects(bucket_id,name) VALUES('time-entry-photos',$1),('time-entry-photos',$2)",[inPhoto,outPhoto]);
 return (await db.query(`INSERT INTO time_entries(id,contractor_id,ticket_id,storm_event_id,clock_in_at,clock_out_at,work_type,work_type_rate,clock_in_latitude,clock_in_longitude,clock_in_accuracy,clock_in_photo_url,clock_out_latitude,clock_out_longitude,clock_out_accuracy,clock_out_photo_url,activity_intervals)
 VALUES($1,$2,$2,$3,$4,$5,$6,999,32.5,-93.7,10,$7,32.5,-93.7,10,$8,$9) RETURNING *`,[id,worker,storm,start,end,type,inPhoto,outPhoto,activities])).rows[0];
}
for (const type of ['STANDARD_ASSESSMENT','EMERGENCY_RESPONSE','TRAVEL','STANDBY','ADMIN','TRAINING']) await db.query('INSERT INTO utility_billing_rates(work_type,hourly_rate) VALUES($1,175)',[type]);
await test('migration preserves legacy snapshots and seeds saved override values',async()=>{const row=(await db.query('SELECT * FROM time_entries WHERE contractor_id=$1',[legacyId])).rows[0];assert.equal(Number(row.payroll_amount),77);assert.equal(Number(row.utility_bill_amount),101);assert.equal(row.calculation_version,'LEGACY');const agreement=(await db.query('SELECT terms FROM contractor_pay_agreements WHERE contractor_id=$1',[legacyId])).rows[0].terms;assert.equal(agreement.base_hourly_rate,65);assert.equal(agreement.work_type_rates.TRAVEL,75);});
await test('all five pay roles and all six work types use saved wages',async()=>{const roles=['STORM_MANAGER','TEAM_LEAD','SR_DAMAGE_ASSESSER','DAMAGE_ASSESSER','DRIVER'];const types=['STANDARD_ASSESSMENT','EMERGENCY_RESPONSE','TRAVEL','STANDBY','ADMIN','TRAINING'];for(let role=0;role<roles.length;role++)for(const type of types){const rate=[115,105,95,85,65][role];const id=await worker(undefined,roles[role],rate);const entry=await shift(id,'2027-01-04T12:00Z','2027-01-05T04:00Z',[],type);assert.equal(Number(entry.payroll_amount),16*rate);assert.equal(entry.contractor_role,roles[role]);}});
for(const [mult,expected] of [[1,1040],[1.5,1560],[2,2080]]) await test(`16 hours at saved flat ${mult}x`,async()=>{const id=await worker({mode:'FLAT',multiplier:mult});const entry=await shift(id,'2027-01-04T12:00Z','2027-01-05T04:00Z');assert.equal(Number(entry.payroll_amount),expected);assert.equal(Number(entry.paid_minutes_exact),960);assert.equal(Number(entry.utility_bill_amount),2800);});
const weekly={mode:'WEEKLY_TIERS',tiers:[{after_hours:0,multiplier:1},{after_hours:40,multiplier:1.5},{after_hours:60,multiplier:2}]};
await test('weekly tiers, optional double time, work types, and reset',async()=>{const id=await worker(weekly);let total=0;for(let day=4;day<=7;day++){const entry=await shift(id,`2027-01-0${day}T12:00Z`,`2027-01-0${day+1}T04:00Z`,[],day===6?'STANDARD_ASSESSMENT':'TRAVEL');total+=Number(entry.payroll_amount);if(day===6)assert.equal(total,3380);}assert.equal(total,5070);const entry=await shift(id,'2027-01-11T12:00Z','2027-01-11T13:00Z');assert.equal(Number(entry.payroll_amount),65);});
await test('effective mid-shift wage change',async()=>{const id=await worker();await agreement(id,'2027-01-04T20:00Z',terms(undefined,75));const entry=await shift(id,'2027-01-04T12:00Z','2027-01-05T04:00Z');assert.equal(Number(entry.payroll_amount),1120);assert.equal(entry.pay_segments.length,2);});
await test('actual break spanning a rate change',async()=>{const id=await worker();await agreement(id,'2027-01-04T20:00Z',terms(undefined,75));const entry=await shift(id,'2027-01-04T12:00Z','2027-01-05T04:00Z',[interval('BREAK','2027-01-04T19:30:00Z','2027-01-04T20:30:00Z')]);assert.equal(Number(entry.payroll_amount),1050);assert.equal(Number(entry.paid_minutes_exact),900);});
await test('vehicle allowance is segmented and separate from multipliers',async()=>{const id=await worker({mode:'FLAT',multiplier:2});await agreement(id,'2027-01-04T13:00Z',{...terms({mode:'FLAT',multiplier:2}),vehicle_hourly_rate:7});const entry=await shift(id,'2027-01-04T12:00Z','2027-01-04T15:00Z',[interval('VEHICLE_USE','2027-01-04T12:00:00Z','2027-01-04T14:00:00Z')]);assert.equal(Number(entry.vehicle_allowance_amount),12);assert.equal(Number(entry.vehicle_minutes),120);const claim=(await db.query('INSERT INTO time_entry_vehicle_claims(time_entry_id,contractor_id,declared_hours,notes,vehicle_photo_url,license_plate_photo_url) VALUES($1,$2,999,\'Used vehicle\',$3,$4) RETURNING *',[entry.id,id,`${id}/time-entries/${entry.id}/vehicle`,`${id}/time-entries/${entry.id}/plate`])).rows[0];assert.equal(Number(claim.amount),12);assert.equal(Number(claim.declared_hours),2);});
await test('custom thresholds and policy changes retain cross-storm weekly hours',async()=>{
 const id=await worker({mode:'FLAT',multiplier:2});await shift(id,'2027-01-04T12:00Z','2027-01-05T04:00Z');
 await agreement(id,'2027-01-05T06:00Z',terms({mode:'WEEKLY_TIERS',tiers:[{after_hours:0,multiplier:1},{after_hours:20,multiplier:1.25}]}));
 const secondStorm=randomUUID();await db.query('UPDATE tickets SET storm_event_id=$1 WHERE id=$2',[secondStorm,id]);
 const previousStorm=storm;storm=secondStorm;
 try {const entry=await shift(id,'2027-01-05T12:00Z','2027-01-05T20:00Z');assert.equal(Number(entry.payroll_amount),585);} finally {storm=previousStorm;}
});
await test('vehicle eligibility changes stop allowance at their effective time',async()=>{const id=await worker();await agreement(id,'2027-01-04T13:00Z',{...terms(),driver_eligible:false,vehicle_allowance_enabled:false,vehicle_hourly_rate:0});const entry=await shift(id,'2027-01-04T12:00Z','2027-01-04T14:00Z',[interval('VEHICLE_USE','2027-01-04T12:00:00Z','2027-01-04T14:00:00Z')]);assert.equal(Number(entry.vehicle_allowance_amount),5);assert.equal(Number(entry.vehicle_minutes),60);});
await test('workweek boundary splits elapsed paid time around breaks',async()=>{const id=await worker({mode:'WEEKLY_TIERS',tiers:[{after_hours:0,multiplier:1},{after_hours:1,multiplier:2}]});const entry=await shift(id,'2027-01-10T23:00Z','2027-01-11T08:00Z',[interval('BREAK','2027-01-11T05:30:00Z','2027-01-11T06:30:00Z')]);assert.equal(Number(entry.paid_minutes_exact),480);assert.equal(Number(entry.payroll_amount),910);assert.equal(new Set(entry.pay_segments.map(s=>s.week_start_at)).size,2);});
await test('invalid compensation, tiers, workweek edits and backdating',async()=>{const id=await worker();await assert.rejects(()=>agreement(id,'2027-01-05T06:00Z',terms({mode:'WEEKLY_TIERS',tiers:[{after_hours:1,multiplier:1}]})),/start at zero/);await assert.rejects(()=>agreement(id,'2027-01-05T06:00Z',{...terms(),timezone:'Invalid/Zone'}),/Invalid compensation/);await assert.rejects(()=>agreement(id,'2027-01-05T06:00Z',{...terms(),week_start_day:2}),/boundary/);const entry=await shift(id,'2027-01-04T12:00Z','2027-01-04T13:00Z');await assert.rejects(()=>agreement(id,'2027-01-04T12:30Z',terms()),/closed payroll/);await assert.rejects(()=>db.query('UPDATE contractor_pay_agreements SET terms=$1 WHERE contractor_id=$2',[terms(),id]),/immutable/);});
await test('scheduled workweek transitions remain valid and current operational role updates',async()=>{const id=await worker();await agreement(id,'2027-01-18T06:00Z',{...terms(),week_start_day:2});await assert.rejects(()=>agreement(id,'2027-01-11T06:00Z',{...terms(),week_start_day:3}),/scheduled workweek/);await agreement(id,new Date().toISOString(),{...terms(),role:'TEAM_LEAD'});assert.equal((await db.query('SELECT role FROM contractors WHERE id=$1',[id])).rows[0].role,'TEAM_LEAD');});
await test('interval overlap, duplicates, GPS, photo and shift validation',async()=>{const id=await worker();await assert.rejects(()=>shift(id,'2027-01-04T12:00Z','2027-01-04T16:00Z',[interval('BREAK','2027-01-04T13:00:00Z','2027-01-04T14:00:00Z'),interval('VEHICLE_USE','2027-01-04T13:30:00Z','2027-01-04T15:00:00Z')]),/overlap/);await assert.rejects(()=>shift(id,'2027-01-04T12:00Z','2027-01-05T15:00Z'),/duration/);await assert.rejects(()=>db.query("INSERT INTO time_entries(contractor_id,ticket_id,storm_event_id,clock_in_at,work_type,work_type_rate,clock_in_latitude,clock_in_longitude,clock_in_accuracy) VALUES($1,$1,$2,'2027-01-04T12:00Z','TRAVEL',1,32,-93,10)",[id,storm]),/photo/);});
await test('closed money snapshots and inputs stay immutable',async()=>{const id=await worker();const entry=await shift(id,'2027-01-04T12:00Z','2027-01-04T13:00Z');await agreement(id,'2027-01-05T12:00Z',terms(undefined,99));await db.query('UPDATE time_entries SET payroll_amount=1,utility_bill_amount=1,vehicle_allowance_amount=999 WHERE id=$1',[entry.id]);const stored=(await db.query('SELECT * FROM time_entries WHERE id=$1',[entry.id])).rows[0];assert.equal(Number(stored.payroll_amount),65);assert.equal(Number(stored.utility_bill_amount),175);assert.equal(Number(stored.vehicle_allowance_amount),0);await assert.rejects(()=>db.query("UPDATE time_entries SET clock_out_photo_url='changed' WHERE id=$1",[entry.id]),/evidence is immutable/);await assert.rejects(()=>db.query('UPDATE time_entries SET clock_out_at=NULL WHERE id=$1',[entry.id]),/immutable/);});
await test('DST elapsed time and exact sub-minute breaks',async()=>{const id=await worker();const entry=await shift(id,'2027-11-07T05:00Z','2027-11-07T10:00Z',[interval('BREAK','2027-11-07T06:00:00Z','2027-11-07T06:00:30Z')]);assert.equal(Number(entry.paid_minutes_exact),299.5);assert.equal(Number(entry.payroll_amount),324.46);assert.equal(entry.pay_segments.reduce((sum,segment)=>sum+Number(segment.wage_amount),0).toFixed(2),'324.46');});
await test('Admin edit overrides never grant writes or confidential reads',async()=>{await db.query("INSERT INTO user_permissions VALUES($1,'admin.time.edit','allow'),($1,'admin.payroll.edit','allow')",[admin]);await db.query("SELECT set_config('test.actor_id',$1,false)",[admin]);assert.equal((await db.query("SELECT private.has_permission(auth.uid(),'admin.time.edit') AS allowed")).rows[0].allowed,false);await db.exec('SET ROLE authenticated');await assert.rejects(()=>db.query('SELECT utility_bill_amount FROM time_entries'),/permission denied/);await assert.rejects(()=>db.query('SELECT * FROM time_entries'),/permission denied/);assert.ok((await db.query('SELECT id,payroll_amount FROM time_entries')).rows.length>0);assert.equal((await db.query('SELECT * FROM utility_billing_rates')).rows.length,0);await assert.rejects(()=>db.query('SELECT get_privileged_payroll_entries()'),/denied/);assert.equal((await db.query("UPDATE time_entries SET status='APPROVED' RETURNING id")).rows.length,0);await db.exec('RESET ROLE');await db.query("SELECT set_config('test.actor_id',$1,false)",[sa]);});
await test('contractor ownership survives broad permissive policies',async()=>{const id=await worker();await db.query("SELECT set_config('test.actor_id',$1,false)",[id]);await db.exec('SET ROLE authenticated');assert.equal((await db.query('SELECT id FROM contractors')).rows.length,1);assert.equal((await db.query('SELECT id FROM time_entries WHERE contractor_id<>$1',[id])).rows.length,0);await assert.rejects(()=>db.query('SELECT get_privileged_payroll_entries()'),/denied/);await db.exec('RESET ROLE');await db.query("SELECT set_config('test.actor_id',$1,false)",[sa]);});
await test('CEO and Super Admin can access guarded billing and review',async()=>{for(const actor of [ceo,sa]){await db.query("SELECT set_config('test.actor_id',$1,false)",[actor]);await db.exec('SET ROLE authenticated');const rows=(await db.query('SELECT get_privileged_payroll_entries() result')).rows[0].result;assert.ok(rows.length>0);assert.ok(rows[0].utility_bill_amount);await db.exec('RESET ROLE');}});
await test('invitation setup binds once and retries preserve agreement history',async()=>{const id=await worker();await db.query('INSERT INTO contractor_invitation_pay_setups(email,actor_id,terms) VALUES($1,$2,$3)',['retry@example.test',sa,terms()]);await db.query("SELECT set_config('test.actor_id','',false)");await db.exec('SET ROLE service_role');const first=(await db.query("SELECT complete_invitation_pay_setup($1,$2,'retry@example.test') id",[sa,id])).rows[0].id;const second=(await db.query("SELECT complete_invitation_pay_setup($1,$2,'retry@example.test') id",[sa,id])).rows[0].id;assert.equal(first,second);await assert.rejects(()=>db.query("SELECT complete_invitation_pay_setup($1,$2,'retry@example.test')",[admin,id]),/Privileged/);await db.exec('RESET ROLE');await db.query("SELECT set_config('test.actor_id',$1,false)",[sa]);});
await writeFile(new URL('../../docs/testing/configurable-payroll-local.json',import.meta.url),JSON.stringify({verifiedAt:new Date().toISOString(),environment:'isolated PGlite; not live or physical device evidence',tests,passed:tests.length},null,2)+'\n');
console.log(`${tests.length} database suites passed.`);await db.close();
