import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {randomUUID as uuid} from 'node:crypto';
const runtime=process.env.CC_PGLITE_PATH||'/Users/davidmccarty/.codex/.chatgpt-projects/g-p-698e4e3dea2c819193d268ef77b9572e/workspace/e2e-20261001/policy-runtime/node_modules/@electric-sql/pglite/dist/index.js';
const {PGlite}=await import(pathToFileURL(runtime).href);const db=new PGlite();
await db.exec(`CREATE SCHEMA private;CREATE SCHEMA auth;CREATE SCHEMA storage;CREATE ROLE authenticated;CREATE ROLE anon;
CREATE TYPE user_role AS ENUM('CEO','SUPER_ADMIN','ADMIN','CONTRACTOR');
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$SELECT nullif(current_setting('test.actor',true),'')::uuid$$;
CREATE TABLE profiles(id uuid PRIMARY KEY,role user_role,is_active boolean DEFAULT true,must_reset_password boolean DEFAULT false);
CREATE TABLE contractors(id uuid PRIMARY KEY,profile_id uuid,is_deleted boolean DEFAULT false);
CREATE TABLE tickets(id uuid PRIMARY KEY,ticket_number text,team_lead_id uuid,assigned_to uuid,assigned_driver_id uuid,status text,is_deleted boolean DEFAULT false,utility_client text DEFAULT 'ENTERGY');
CREATE TABLE user_permissions(profile_id uuid,permission_key text,effect text);
CREATE FUNCTION private.active_profile_role() RETURNS text LANGUAGE sql SECURITY DEFINER AS $$SELECT role::text FROM public.profiles WHERE id=auth.uid() AND is_active AND NOT must_reset_password$$;
CREATE FUNCTION private.contractor_portal_ready() RETURNS boolean LANGUAGE sql AS $$SELECT private.active_profile_role() IS NOT NULL$$;
CREATE FUNCTION private.has_permission(p_id uuid,p_key text) RETURNS boolean LANGUAGE sql SECURITY DEFINER AS $$SELECT private.active_profile_role() IN ('ADMIN','CEO','SUPER_ADMIN') AND NOT EXISTS(SELECT 1 FROM public.user_permissions WHERE profile_id=p_id AND permission_key=p_key AND effect='deny')$$;
CREATE TABLE damage_assessments(id uuid PRIMARY KEY,ticket_id uuid,photo_evidence jsonb);
CREATE TABLE media_assets(id uuid PRIMARY KEY,entity_type text,entity_id uuid,upload_status text,storage_bucket text,storage_path text,gps_latitude numeric,gps_longitude numeric,checksum_sha256 text,uploaded_by uuid,updated_at timestamptz);
CREATE TABLE storage.objects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),bucket_id text,name text);
CREATE TABLE audit_logs(action text,entity_type text,entity_id uuid,user_id uuid,user_role user_role,old_values jsonb,new_values jsonb,change_summary text);
GRANT USAGE ON SCHEMA public,private,auth,storage TO authenticated;`);
const workflow=await readFile('supabase/migrations/20261006123214_ticket_draft_crew_review_workflow.sql','utf8');
const access=workflow.slice(workflow.indexOf('CREATE OR REPLACE FUNCTION private.can_access_ticket'),workflow.indexOf('ALTER TABLE public.field_crews ENABLE ROW LEVEL SECURITY;'));
await db.exec(access);
await db.exec(await readFile('supabase/migrations/20261006175056_entergy_official_ticket_forms.sql','utf8'));
await db.exec(await readFile('supabase/migrations/20261006175923_remove_entergy_lighting_map.sql','utf8'));
await db.exec(`CREATE TRIGGER guard_media BEFORE UPDATE ON media_assets FOR EACH ROW EXECUTE FUNCTION private.guard_submitted_ticket_media();
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;CREATE POLICY photos_write ON storage.objects FOR UPDATE TO authenticated USING(private.ticket_photo_access(name,true)) WITH CHECK(private.ticket_photo_access(name,true));GRANT SELECT,UPDATE ON storage.objects TO authenticated;`);
const chief=uuid(),lead=uuid(),unrelated=uuid(),assessor=uuid(),driver=uuid(),aid=uuid(),did=uuid(),ticket=uuid(),otherTicket=uuid();
await db.query("INSERT INTO profiles(id,role) VALUES($1,'SUPER_ADMIN'),($2,'ADMIN'),($3,'ADMIN'),($4,'CONTRACTOR'),($5,'CONTRACTOR')",[chief,lead,unrelated,assessor,driver]);
await db.query('INSERT INTO contractors VALUES($1,$2),($3,$4)',[aid,assessor,did,driver]);
await db.query("INSERT INTO tickets(id,ticket_number,team_lead_id,assigned_to,assigned_driver_id,status) VALUES($1,'QA-ENTERGY',$2,$3,$4,'ON_SITE'),($5,'OTHER',$6,NULL,NULL,'ON_SITE')",[ticket,lead,aid,did,otherTicket,unrelated]);
const spec=JSON.parse(await readFile('src/lib/config/entergyForms.json','utf8'));
function blank(kind){const fields=spec[kind].sections.filter(s=>!s.repeat).flatMap(s=>s.fields);const answers=Object.fromEntries(fields.map(f=>[f.key,f.kind==='multi'?[]:null]));const repeat=(name)=>{const s=spec[kind].sections.find(s=>s.repeat?.key===name);return s?Array.from({length:s.repeat.minimumRows},(_,i)=>Object.fromEntries(s.fields.map(f=>[f.key,f.key==='operation'?i%2?'Remove':'Install':f.kind==='multi'?[]:null]))):[];};return {version:1,answers,equipmentRows:repeat('equipmentRows'),customerRows:repeat('customerRows'),lightingMap:[],damageReports:{}};}
const clean=blank('cleanup');Object.assign(clean.answers,{environmentalCleanup:'None',trashCleanup:'Wood: 2 poles',address:'100 Utility Lane',cityTown:'Shreveport',dloc:'00000001234',truckAccess:false,notes:'Blocked gate'});
const damage=blank('damage');Object.assign(damage.answers,{date:'2026-10-06',equipmentTypes:['Pole'],activities:['Install/Remove'],fromDloc:'00000001234',fieldAddressComments:'100 Utility Lane',signature:'QA Assessor',workOrderNumber:'00042',employeeId:'C001'});
const json=x=>JSON.stringify(x);const checks=[];async function test(name,operation){await operation();checks.push(name);}
async function actor(id){await db.exec('RESET ROLE');await db.query("SELECT set_config('test.actor',$1,false)",[id]);await db.exec('SET ROLE authenticated');}
async function save(id,kind,payload,photos=[],version=null,submit=false,target=ticket){return (await db.query('SELECT * FROM public.save_entergy_ticket_form($1,$2,$3,$4::jsonb,$5::jsonb,$6,$7)',[id,target,kind,json(payload),json(photos),version,submit])).rows[0];}
const cleanupId=uuid(),damageId=uuid();await actor(assessor);
await test('allows incomplete cleanup draft before evidence capture',async()=>{const row=await save(cleanupId,'cleanup',blank('cleanup'));assert.equal(row.status,'DRAFT');assert.equal(row.saved_by,assessor);});
await test('saves separate cleanup and damage drafts on the same ticket',async()=>{await save(damageId,'damage',damage);assert.equal((await db.query('SELECT * FROM ticket_entergy_forms')).rows.length,2);});
await test('rejects stale writes across devices',async()=>{await save(cleanupId,'cleanup',clean,[],1);await assert.rejects(()=>save(cleanupId,'cleanup',{...clean,answers:{...clean.answers,notes:'Stale'}},[],1),/another device/);});
await test('retries exact saved content without another revision',async()=>assert.equal((await save(cleanupId,'cleanup',clean,[],1)).version,2));
await test('retains identifier leading zeros',async()=>assert.equal((await db.query('SELECT payload FROM ticket_entergy_forms WHERE id=$1',[cleanupId])).rows[0].payload.answers.dloc,'00000001234'));
await test('rejects a second draft for the same form kind',async()=>assert.rejects(()=>save(uuid(),'cleanup',clean),/draft already exists/));
await test('rejects malformed and forged choices even in drafts',async()=>assert.rejects(()=>save(damageId,'damage',{...damage,answers:{...damage.answers,equipmentTypes:['Unknown']}},[],1),/checkbox choices/));
await test('rejects unknown fields',async()=>assert.rejects(()=>save(damageId,'damage',{...damage,answers:{...damage.answers,unexpected:'value'}},[],1),/Unknown form field/));
await test('rejects invalid date',async()=>assert.rejects(()=>save(damageId,'damage',{...damage,answers:{...damage.answers,date:'2026-02-30'}},[],1),/Invalid date/));
await test('rejects damage fields in cleanup',async()=>assert.rejects(()=>save(cleanupId,'cleanup',{...clean,equipmentRows:[{}]},[],2),/Damage fields/));
await test('requires complete fields and four photo views at submission',async()=>{await assert.rejects(()=>save(cleanupId,'cleanup',blank('cleanup'),[],2,true),/Complete/);await assert.rejects(()=>save(cleanupId,'cleanup',clean,[],2,true),/Four GPS/);});
await test('lighting changes no longer require a map',async()=>assert.rejects(()=>save(damageId,'damage',{...damage,answers:{...damage.answers,equipmentTypes:['Streetlight'],activities:['Install']}},[],1,true),/Four GPS/));
await test('invalid map coordinates are rejected',async()=>assert.rejects(()=>save(damageId,'damage',{...damage,lightingMap:[{points:[[0,0],[1001,600]]}]},[],1),/out of bounds/));
await test('used customer transfers need every row value',async()=>{const p=structuredClone(damage);p.customerRows[0].identifier='000001';await assert.rejects(()=>save(damageId,'damage',p,[],1,true),/customer transfer/);});
await actor(driver);
await test('assigned driver can read but cannot edit assessor forms',async()=>{assert.equal((await db.query('SELECT * FROM ticket_entergy_forms')).rows.length,2);await assert.rejects(()=>save(uuid(),'damage',damage),/Assigned assessor/);});
await actor(lead);
await test('assigned team lead can read records',async()=>assert.equal((await db.query('SELECT * FROM ticket_entergy_forms')).rows.length,2));
await test('team lead cannot bypass assessor write scope',async()=>assert.rejects(()=>save(uuid(),'cleanup',clean),/Assigned assessor/));
await actor(unrelated);
await test('unrelated staff cannot read or edit another team ticket',async()=>{assert.equal((await db.query('SELECT * FROM ticket_entergy_forms')).rows.length,0);await assert.rejects(()=>save(uuid(),'cleanup',clean),/Assigned assessor/);});
await actor(chief);
await test('authorized chief can edit the saved draft',async()=>assert.equal((await save(cleanupId,'cleanup',clean,[],2)).saved_by,chief));
await db.exec('RESET ROLE');await db.query("INSERT INTO user_permissions VALUES($1,'admin.assessments.view','deny')",[lead]);await actor(lead);
await test('assessment-view denial hides official records',async()=>assert.equal((await db.query('SELECT * FROM ticket_entergy_forms')).rows.length,0));
await actor(assessor);
const photos=['OVERVIEW','EQUIPMENT','DAMAGE','SAFETY'].map(type=>({id:uuid(),type,gpsLatitude:32.4,gpsLongitude:-93.7,checksumSha256:'abc123'}));
await test('unuploaded or wrong-ticket evidence cannot submit',async()=>assert.rejects(()=>save(cleanupId,'cleanup',clean,photos,3,true),/upload is incomplete/));
await db.exec('RESET ROLE');for(const photo of photos){const path=`${assessor}/tickets/${ticket}/${photo.id}-original.jpg`;await db.query("INSERT INTO media_assets VALUES($1,'ticket',$2,'COMPLETED','assessment-photos',$3,32.4,-93.7,'abc123',$4,now())",[photo.id,ticket,path,assessor]);await db.query("INSERT INTO storage.objects(bucket_id,name) VALUES('assessment-photos',$1)",[path]);}
await actor(assessor);
await test('submits linked uploaded GPS evidence and binds identity',async()=>{const row=await save(cleanupId,'cleanup',clean,photos,3,true);assert.equal(row.status,'SUBMITTED');assert.equal(row.saved_by,assessor);assert.equal(row.payload.answers.truckAccess,false);assert.ok(row.submitted_at);});
await test('submitted retry returns the same immutable version',async()=>assert.equal((await save(cleanupId,'cleanup',clean,photos,3,true)).version,4));
await test('submitted form edits are rejected',async()=>assert.rejects(()=>save(cleanupId,'cleanup',{...clean,answers:{...clean.answers,notes:'Edited'}},photos,4),/immutable/));
await test('new revisions can start without overwriting prior submissions',async()=>{await save(uuid(),'cleanup',clean);assert.equal((await db.query("SELECT * FROM ticket_entergy_forms WHERE status='SUBMITTED'")).rows.length,1);});
await test('submitted Entergy originals and thumbnails cannot be overwritten',async()=>{const path=`${assessor}/tickets/${ticket}/${photos[0].id}-original.jpg`;assert.equal((await db.query('SELECT private.ticket_photo_access($1,true) allowed',[path])).rows[0].allowed,false);assert.equal((await db.query('SELECT private.ticket_photo_access($1,true) allowed',[path.replace('original','thumbnail')])).rows[0].allowed,false);});
await db.exec('RESET ROLE');
await test('submitted photo metadata is immutable',async()=>assert.rejects(()=>db.query('UPDATE media_assets SET gps_latitude=33 WHERE id=$1',[photos[0].id]),/immutable/));
await actor(assessor);
await test('section damage needs its own linked photo',async()=>assert.rejects(()=>save(damageId,'damage',{...damage,damageReports:{pole:'Split at base'}},photos,1,true),/inside section/));
await test('mismatched section evidence is rejected',async()=>assert.rejects(()=>save(damageId,'damage',damage,photos.map(p=>p.type==='DAMAGE'?{...p,sectionKey:'entergy:pole'}:p),1,true),/does not match/));
await test('photo checksum must match stored metadata',async()=>assert.rejects(()=>save(damageId,'damage',damage,photos.map(p=>({...p,checksumSha256:'wrong'})),1,true),/upload is incomplete/));
await test('cross-ticket identity cannot be reused',async()=>assert.rejects(()=>save(damageId,'damage',damage,[],1,false,otherTicket),/Assigned assessor/));
await test('authenticated users cannot write directly around RPC validation',async()=>assert.rejects(()=>db.query("UPDATE ticket_entergy_forms SET status='SUBMITTED' WHERE id=$1",[damageId]),/permission denied/));
await db.exec('RESET ROLE');await db.query('UPDATE profiles SET is_active=false WHERE id=$1',[assessor]);await actor(assessor);
await test('inactive assessor loses all read and write access',async()=>{assert.equal((await db.query('SELECT * FROM ticket_entergy_forms')).rows.length,0);await assert.rejects(()=>save(uuid(),'cleanup',clean),/Assigned assessor/);});
await db.exec('RESET ROLE');await db.query("SELECT set_config('test.actor','',false)");await db.exec('SET ROLE anon');
await test('anonymous roles cannot read or invoke the form RPC',async()=>{await assert.rejects(()=>db.query('SELECT * FROM ticket_entergy_forms'),/permission denied/);await assert.rejects(()=>save(uuid(),'cleanup',clean),/permission denied/);});
await db.exec('RESET ROLE');await test('saves and submissions emit server-bound audit events',async()=>{const rows=(await db.query('SELECT * FROM audit_logs')).rows;assert.ok(rows.some(r=>r.action==='ENTERGY_FORM_SUBMITTED'&&r.user_id===assessor));});
await db.close();await writeFile('docs/testing/entergy-forms-database.json',json({scope:'Exact new migration in isolated PGlite with copied ticket-access helpers and fixture auth/profile permission checks. Not live sign-in or actual Storage API upload evidence.',passed:checks.length,checks})+'\n');console.log(`${checks.length} Entergy database checks passed`);
