import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { randomUUID } from 'node:crypto';
const runtime = process.env.CC_PGLITE_PATH || '/Users/davidmccarty/.codex/.chatgpt-projects/g-p-698e4e3dea2c819193d268ef77b9572e/workspace/e2e-20261001/policy-runtime/node_modules/@electric-sql/pglite/dist/index.js';
const { PGlite } = await import(pathToFileURL(runtime).href);
const db = new PGlite();
const migration = await readFile('supabase/migrations/20261005131753_top_down_ticket_assessments.sql','utf8');
const sections = JSON.parse(await readFile('src/lib/config/fieldAssessment.json','utf8'));
const fields = sections.flatMap(s=>s.fields);
const answers=Object.fromEntries([...fields.map(f=>[f.key,f.when?null:f.kind==='boolean'?false:f.kind==='select'?f.options[0]:'None']),['additionalNotes','None']]);
const payload={version:1,answers};
const photos=['OVERVIEW','EQUIPMENT','DAMAGE','SAFETY'].map(type=>({id:randomUUID(),type,gpsLatitude:30,gpsLongitude:-90}));
await db.exec(`CREATE SCHEMA private; CREATE SCHEMA auth; CREATE ROLE authenticated; CREATE ROLE anon;
CREATE TYPE user_role AS ENUM('CONTRACTOR','ADMIN','SUPER_ADMIN','CEO'); CREATE TYPE priority_level AS ENUM('A','B','C','X');
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('test.actor',true),'')::uuid $$;
CREATE TABLE profiles(id uuid PRIMARY KEY,role user_role,is_active boolean DEFAULT true);
CREATE TABLE contractors(id uuid PRIMARY KEY,profile_id uuid,is_deleted boolean DEFAULT false);
CREATE FUNCTION private.active_profile_role() RETURNS text LANGUAGE sql SECURITY DEFINER AS $$ SELECT role::text FROM public.profiles WHERE id=auth.uid() AND is_active $$;
CREATE FUNCTION private.contractor_portal_ready() RETURNS boolean LANGUAGE sql AS $$ SELECT private.active_profile_role() IS NOT NULL $$;
CREATE FUNCTION private.has_permission(uuid,text) RETURNS boolean LANGUAGE sql AS $$ SELECT private.active_profile_role() IN ('ADMIN','SUPER_ADMIN','CEO') $$;
CREATE TABLE tickets(id uuid PRIMARY KEY,assigned_to uuid,status text,is_deleted boolean DEFAULT false,severity text,is_important boolean DEFAULT false,updated_by uuid,updated_at timestamptz);
CREATE TABLE damage_assessments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),ticket_id uuid UNIQUE,contractor_id uuid,assessed_by uuid,assessed_at timestamptz,created_by uuid,created_at timestamptz DEFAULT now(),updated_by uuid,updated_at timestamptz,reviewed_by uuid,reviewed_at timestamptz,review_notes text,priority priority_level,sync_status text,safety_observations jsonb);
CREATE TABLE audit_logs(action text,entity_type text,entity_id uuid,user_id uuid,user_role user_role,old_values jsonb,new_values jsonb,change_summary text);
ALTER TABLE damage_assessments ENABLE ROW LEVEL SECURITY;
CREATE POLICY fixture_own ON damage_assessments FOR ALL TO authenticated USING(contractor_id IN(SELECT id FROM contractors WHERE profile_id=auth.uid()) OR private.has_permission(auth.uid(),'admin.assessments.view')) WITH CHECK(contractor_id IN(SELECT id FROM contractors WHERE profile_id=auth.uid()) OR private.has_permission(auth.uid(),'admin.assessments.edit'));
GRANT USAGE ON SCHEMA public,private,auth TO authenticated; GRANT SELECT ON contractors TO authenticated;
GRANT SELECT,UPDATE ON tickets TO authenticated;
`);
await db.exec(migration);
await db.exec('CREATE TRIGGER aa_guard_worker_ticket_update BEFORE UPDATE ON tickets FOR EACH ROW EXECUTE FUNCTION private.guard_worker_ticket_update()');
const user=randomUUID(),other=randomUUID(),admin=randomUUID(),contractor=randomUUID(),second=randomUUID(),ticket=randomUUID(),otherTicket=randomUUID(),emptyTicket=randomUUID();
await db.query("INSERT INTO profiles VALUES($1,'CONTRACTOR',true),($2,'CONTRACTOR',true),($3,'ADMIN',true)",[user,other,admin]);
await db.query('INSERT INTO contractors(id,profile_id) VALUES($1,$2),($3,$4)',[contractor,user,second,other]);
await db.query("INSERT INTO tickets(id,assigned_to,status) VALUES($1,$2,'IN_PROGRESS'),($3,$4,'IN_PROGRESS'),($5,$2,'IN_PROGRESS')",[ticket,contractor,otherTicket,second,emptyTicket]);
let count=0;const checks=[];
async function pass(label,fn){await fn();checks.push(label);count++;}
async function valid(p){return (await db.query('SELECT private.validate_field_assessment($1::jsonb) ok',[JSON.stringify(p)])).rows[0].ok;}
await pass('complete no-damage checklist accepted',async()=>assert.equal(await valid(payload),true));
for(const f of fields.filter(f=>!f.when)) await pass(`missing ${f.key} rejected`,async()=>{const p=structuredClone(payload);p.answers[f.key]=null;assert.equal(await valid(p),false);});
await pass('invalid predefined conductor size rejected',async()=>{const p=structuredClone(payload);Object.assign(p.answers,{conductorBroken:true,conductorSize:'999',spansDown:'2',conductorDamage:'broken'});assert.equal(await valid(p),false);});
await pass('hidden answers rejected',async()=>{const p=structuredClone(payload);p.answers.poleHeight='40';assert.equal(await valid(p),false);});
await pass('unknown keys rejected',async()=>{const p=structuredClone(payload);p.answers.injected='yes';assert.equal(await valid(p),false);});
await pass('positive integer count required',async()=>{const p=structuredClone(payload);Object.assign(p.answers,{insulatorsBroken:true,insulatorCount:1.5,insulatorDamage:'cracked'});assert.equal(await valid(p),false);});
await db.query("SELECT set_config('test.actor',$1,false)",[user]);await db.exec('SET ROLE authenticated');
const insert=async(t=ticket,p=payload,ph=photos)=>db.query('INSERT INTO damage_assessments(ticket_id,contractor_id,field_assessment,photo_evidence,assessed_by) VALUES($1,$2,$3,$4,$5) RETURNING *',[t,contractor,JSON.stringify(p),JSON.stringify(ph),other]);
const urgent=structuredClone(payload);Object.assign(urgent.answers,{publicDanger:true,publicDangerDetails:'QA public danger'});
let row;
await pass('assigned user creates assessment and identity is server bound',async()=>{row=(await insert(ticket,urgent,[...photos,{id:randomUUID(),type:'DAMAGE',sectionKey:'publicDangerDetails',gpsLatitude:30,gpsLongitude:-90}])).rows[0];assert.equal(row.assessed_by,user);assert.equal(row.priority,'A');});
await pass('hazard atomically raises ticket severity and importance',async()=>{const t=(await db.query('SELECT * FROM tickets WHERE id=$1',[ticket])).rows[0];assert.equal(t.severity,'CRITICAL');assert.equal(t.is_important,true);});
await pass('hazard without section damage photo rejected',async()=>assert.rejects(()=>insert(emptyTicket,urgent),/Damage photo required/));
await pass('general damage photo cannot substitute for pole evidence',async()=>{const p=structuredClone(payload);Object.assign(p.answers,{poleBroken:true,poleHeight:'40',poleAccessible:true,poleDamage:'Broken'});await assert.rejects(()=>insert(emptyTicket,p),/Damage photo required/);});
await pass('duplicate photo identifiers rejected',async()=>assert.rejects(()=>insert(emptyTicket,payload,photos.map(p=>({...p,id:photos[0].id}))),/unique identifier/));
await pass('photo in a no-damage section rejected',async()=>assert.rejects(()=>insert(emptyTicket,payload,[...photos,{...photos[2],id:randomUUID(),sectionKey:'poleDamage'}]),/does not match/));
await pass('independent cross arm and insulator photos required',async()=>{const p=structuredClone(payload);Object.assign(p.answers,{hasCrossArm:true,crossArmMaterial:'WOOD',crossArmsDamaged:true,crossArmCount:1,crossArmDamage:'Broken',insulatorsBroken:true,insulatorCount:1,insulatorDamage:'Cracked'});await assert.rejects(()=>insert(emptyTicket,p,[...photos,{...photos[2],id:randomUUID(),sectionKey:'crossArmDamage'}]),/insulatorDamage/);});
await pass('cannot submit on another ticket',async()=>assert.rejects(()=>insert(otherTicket),/assigned ticket/));
await pass('three photos rejected',async()=>assert.rejects(()=>insert(emptyTicket,payload,photos.slice(0,3)),/Four photo/));
await pass('missing photo GPS rejected',async()=>assert.rejects(()=>insert(emptyTicket,payload,photos.map(p=>({...p,gpsLatitude:null}))),/GPS/));
await pass('contractor cannot alter submitted assessment',async()=>{const r=await db.query("UPDATE damage_assessments SET review_notes='forged' WHERE id=$1 RETURNING id",[row.id]);assert.equal(r.rows.length,0);});
await pass('direct contractor priority changes remain forbidden',async()=>assert.rejects(()=>db.query("UPDATE tickets SET severity='LOW' WHERE id=$1",[ticket]),/limited to status/));
await pass('ticket cannot complete without assessment',async()=>assert.rejects(()=>db.query("UPDATE tickets SET status='COMPLETE' WHERE id=$1",[emptyTicket]),/assessment before/));
await pass('ticket with assessment can complete',async()=>{await db.query("UPDATE tickets SET status='COMPLETE' WHERE id=$1",[ticket]);});
await db.exec('RESET ROLE');await db.query("SELECT set_config('test.actor',$1,false)",[admin]);await db.exec('SET ROLE authenticated');
await pass('staff reviewer identity and timestamp server bound',async()=>{const r=(await db.query("UPDATE damage_assessments SET review_notes='[APPROVED] QA',reviewed_by=$2 WHERE id=$1 RETURNING *",[row.id,other])).rows[0];assert.equal(r.reviewed_by,admin);assert.ok(r.reviewed_at);});
await pass('reviewer cannot rewrite field answers',async()=>assert.rejects(()=>db.query('UPDATE damage_assessments SET field_assessment=$2 WHERE id=$1',[row.id,JSON.stringify(payload)]),/immutable/));
await db.exec('RESET ROLE');
await pass('escalation audit is linked to same ticket and assessment',async()=>{const r=(await db.query('SELECT * FROM audit_logs')).rows[0];assert.equal(r.entity_id,ticket);assert.equal(r.new_values.assessment_id,row.id);});
await db.close();
await writeFile('docs/testing/field-assessments-local.json',JSON.stringify({scope:'Isolated PGlite fixture, exact migration; not live RLS or device proof',passed:count,checks},null,2)+'\n');
console.log(`${count} field assessment database checks passed`);
