import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
const runtime = process.env.CC_PGLITE_PATH || '/Users/davidmccarty/.codex/.chatgpt-projects/g-p-698e4e3dea2c819193d268ef77b9572e/workspace/e2e-20261001/policy-runtime/node_modules/@electric-sql/pglite/dist/index.js';
const { PGlite } = await import(pathToFileURL(runtime).href);
const db = new PGlite();
await db.exec(`CREATE SCHEMA auth; CREATE SCHEMA private;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT '00000000-0000-0000-0000-000000000009'::uuid $$;
CREATE FUNCTION private.active_profile_role() RETURNS text LANGUAGE sql AS $$ SELECT current_setting('test.actor_role',true) $$;
CREATE TYPE public.contractor_role AS ENUM ('DRIVER','DAMAGE_ASSESSER');
CREATE TABLE contractors(id uuid PRIMARY KEY,role contractor_role,is_deleted boolean DEFAULT false);
CREATE TABLE contractor_rates(contractor_id uuid,work_type text,hourly_rate numeric,effective_from date,effective_to date);
CREATE TABLE role_rate_defaults(role contractor_role,work_type text,hourly_rate numeric);
CREATE TABLE utility_billing_rates(storm_event_id uuid,work_type text,hourly_rate numeric);
CREATE TABLE time_entries(id uuid PRIMARY KEY,contractor_id uuid,storm_event_id uuid,clock_in_at timestamptz,clock_out_at timestamptz,work_type text,break_minutes integer DEFAULT 0,contractor_role contractor_role,work_type_rate numeric,pay_rate_applied numeric,payroll_amount numeric,utility_bill_rate_applied numeric,utility_bill_amount numeric,status text DEFAULT 'PENDING');
CREATE TABLE time_entry_vehicle_claims(id uuid PRIMARY KEY,time_entry_id uuid,contractor_id uuid,vehicle_type text DEFAULT 'PERSONAL',declared_hours numeric,notes text DEFAULT 'Vehicle used for shift',vehicle_photo_url text DEFAULT '00000000-0000-0000-0000-000000000001/time-entries/00000000-0000-0000-0000-000000000003/vehicle.jpg',license_plate_photo_url text DEFAULT '00000000-0000-0000-0000-000000000001/time-entries/00000000-0000-0000-0000-000000000003/plate.jpg',amount numeric DEFAULT 0,capped boolean DEFAULT false,status text DEFAULT 'PENDING',reviewed_by uuid,reviewed_at timestamptz,rejection_reason text);
INSERT INTO contractors VALUES('00000000-0000-0000-0000-000000000001','DRIVER',false),('00000000-0000-0000-0000-000000000002','DAMAGE_ASSESSER',false);
INSERT INTO role_rate_defaults VALUES('DRIVER','TRAVEL',50),('DAMAGE_ASSESSER','TRAVEL',75);
INSERT INTO utility_billing_rates VALUES(null,'TRAVEL',100);
SET test.actor_role='CONTRACTOR';`);
const baseline = JSON.parse(await readFile(new URL('../../supabase/payroll_integrity_baseline.json', import.meta.url),'utf8'));
await db.exec(baseline.functions.map(item=>item.definition.trim()+';').join('\n'));
// Use the exact live attachments, including their old UPDATE OF restriction.
await db.exec(baseline.triggers.map(item=>item.definition+';').join('\n'));
const shiftId='00000000-0000-0000-0000-000000000003';
const driverId='00000000-0000-0000-0000-000000000001';
const claimId='00000000-0000-0000-0000-000000000004';
await db.query("INSERT INTO time_entries(id,contractor_id,clock_in_at,clock_out_at,work_type) VALUES($1,$2,'2026-10-03 08:00Z','2026-10-03 12:00Z','TRAVEL')",[shiftId,driverId]);
await db.exec("UPDATE role_rate_defaults SET hourly_rate=999 WHERE role='DRIVER'; UPDATE time_entries SET status='APPROVED';");
assert.equal((await db.query('SELECT payroll_amount FROM time_entries')).rows[0].payroll_amount,'200.00');
await db.exec('UPDATE time_entries SET payroll_amount=1;');
assert.equal((await db.query('SELECT payroll_amount FROM time_entries')).rows[0].payroll_amount,'1');
await db.exec('UPDATE time_entries SET break_minutes=break_minutes;');
assert.equal((await db.query('SELECT payroll_amount FROM time_entries')).rows[0].payroll_amount,'3996.00');
console.log('Reproduced snapshot-only tampering and closed-shift rate drift when costing inputs are resent using exact live trigger attachments.');
await db.exec(await readFile(new URL('../../supabase/payroll_integrity.sql', import.meta.url),'utf8'));
await db.exec('TRUNCATE time_entries;');
await db.exec("UPDATE role_rate_defaults SET hourly_rate=50 WHERE role='DRIVER';");
await db.query("INSERT INTO time_entries(id,contractor_id,clock_in_at,work_type,work_type_rate) VALUES($1,$2,'2026-10-03 08:00Z','TRAVEL',999)",[shiftId,driverId]);
let count=0;
async function test(name,fn){await fn();count++;console.log(`PASS ${name}`);}
await test('costing guard runs on every update',async()=>{const trigger=(await db.query("SELECT pg_get_triggerdef(oid) AS definition FROM pg_trigger WHERE tgname='tr_apply_time_entry_costing'")).rows[0];assert.match(trigger.definition,/BEFORE INSERT OR UPDATE ON/);});
await test('claim guard runs on every update including status-only review',async()=>{const trigger=(await db.query("SELECT pg_get_triggerdef(oid) AS definition FROM pg_trigger WHERE tgname='tr_compute_vehicle_claim_amount'")).rows[0];assert.match(trigger.definition,/BEFORE INSERT OR UPDATE ON/);});
const shift=async()=> (await db.query('SELECT * FROM time_entries WHERE id=$1',[shiftId])).rows[0];
await test('client wage is replaced by configured rate',async()=>assert.equal((await shift()).work_type_rate,'50.00'));
await test('clock-out resolves wage and billing snapshots',async()=>{await db.query("UPDATE time_entries SET clock_out_at='2026-10-03 12:00Z' WHERE id=$1",[shiftId]);assert.equal((await shift()).payroll_amount,'200.00');assert.equal((await shift()).utility_bill_amount,'400.00');});
await test('review does not recalculate after rates change',async()=>{await db.exec('UPDATE role_rate_defaults SET hourly_rate=999; UPDATE utility_billing_rates SET hourly_rate=999;');await db.query("UPDATE time_entries SET status='APPROVED' WHERE id=$1",[shiftId]);assert.equal((await shift()).payroll_amount,'200.00');assert.equal((await shift()).utility_bill_amount,'400.00');});
await test('client snapshot tampering is overwritten',async()=>{await db.query('UPDATE time_entries SET payroll_amount=1,utility_bill_amount=1 WHERE id=$1',[shiftId]);assert.equal((await shift()).payroll_amount,'200.00');});
await test('closed shift cannot be reopened or have hours changed',async()=>{await assert.rejects(()=>db.query('UPDATE time_entries SET clock_out_at=null WHERE id=$1',[shiftId]),/immutable/);});
const insertClaim=(extra='')=>db.query(`INSERT INTO time_entry_vehicle_claims(id,time_entry_id,contractor_id,declared_hours${extra?',status':''}) VALUES($1,$2,$3,8${extra?",'APPROVED'":''})`,[claimId,shiftId,driverId]);
await test('preapproved claim insertion is rejected',async()=>assert.rejects(()=>insertClaim('approved'),/await administrator/));
await test('claim cannot reference another shift photo',async()=>assert.rejects(()=>db.query("INSERT INTO time_entry_vehicle_claims(id,time_entry_id,contractor_id,declared_hours,vehicle_photo_url) VALUES($1,$2,$3,1,'another/photo.jpg')",[claimId,shiftId,driverId]),/photos must belong/));
await test('driver claim hours and amount are capped',async()=>{await insertClaim();const c=(await db.query('SELECT * FROM time_entry_vehicle_claims')).rows[0];assert.equal(Number(c.declared_hours),4);assert.equal(c.amount,'20.00');assert.equal(c.capped,true);});
await test('contractor cannot approve a claim',async()=>assert.rejects(()=>db.query("UPDATE time_entry_vehicle_claims SET status='APPROVED'"),/Administrator review/));
await test('submitted claim cannot be relinked to another contractor',async()=>assert.rejects(()=>db.query("UPDATE time_entry_vehicle_claims SET contractor_id='00000000-0000-0000-0000-000000000002'"),/same contractor/));
await test('claim cannot be submitted for a non-driver shift',async()=>{await db.query("INSERT INTO time_entries(id,contractor_id,clock_in_at,clock_out_at,work_type) VALUES('00000000-0000-0000-0000-000000000005','00000000-0000-0000-0000-000000000002','2026-10-03 08:00Z','2026-10-03 12:00Z','TRAVEL')");await assert.rejects(()=>db.query("INSERT INTO time_entry_vehicle_claims(id,time_entry_id,contractor_id,declared_hours) VALUES('00000000-0000-0000-0000-000000000006','00000000-0000-0000-0000-000000000005','00000000-0000-0000-0000-000000000002',1)"),/driver shift/);});
await db.exec("SET test.actor_role='SUPER_ADMIN';");
await test('rejection requires a reason',async()=>assert.rejects(()=>db.query("UPDATE time_entry_vehicle_claims SET status='REJECTED'"),/reason required/));
await test('administrator approval preserves capped amount and binds reviewer',async()=>{await db.query("UPDATE time_entry_vehicle_claims SET status='APPROVED',amount=999,reviewed_by=null");const c=(await db.query('SELECT * FROM time_entry_vehicle_claims')).rows[0];assert.equal(c.amount,'20.00');assert.equal(c.capped,true);assert.equal(c.reviewed_by,'00000000-0000-0000-0000-000000000009');});
await test('review cannot be repeated',async()=>assert.rejects(()=>db.query("UPDATE time_entry_vehicle_claims SET status='REJECTED',rejection_reason='Changed mind'"),/already been reviewed/));
await db.close();console.log(`${count} payroll integrity checks passed (isolated PGlite; not live Supabase proof).`);
